const menu = [
  {
    id: 1,
    title: 'pancakes',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-1.jpeg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.`,
  },
  {
    id: 2,
    title: 'Burger and Fries',
    category: 'Dinner',
    price: 16.99,
    img: './images/item-2.jpeg',
    desc: `Quam nulla porttitor massa id neque aliquam vestibulum. Id neque aliquam vestibulum morbi blandit. Augue neque gravida in fermentum. Scelerisque purus semper eget duis.`,
  },
  {
    id: 3,
    title: 'Ice Drink',
    category: 'snacks',
    price: 8.99,
    img: './images/item-3.jpeg',
    desc: `Arcu dui vivamus arcu felis bibendum ut tristique. Diam maecenas sed enim ut sem viverra aliquet. Fringilla urna porttitor rhoncus dolor purus non enim.`,
  },
  {
    id: 4,
    title: 'Eggs',
    category: 'breakfast',
    price: 16.99,
    img: './images/item-4.jpeg',
    desc: `Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Id donec ultrices tincidunt arcu non sodales neque sodales.`,
  },
  {
    id: 5,
    title: 'Burger',
    category: 'Dinner',
    price: 15.99,
    img: './images/item-5.jpeg',
    desc: `Felis eget nunc lobortis mattis aliquam. Orci dapibus ultrices in iaculis. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.`,
  },
  {
    id: 6,
    title: 'Cookie Drink',
    category: 'snacks',
    price: 16.99,
    img: './images/item-6.jpeg',
    desc: `Amet risus nullam eget felis eget nunc lobortis mattis. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Lacus sed viverra tellus in hac habitasse platea dictumst. Porttitor lacus luctus accumsan tortor posuere ac ut.`,
  },
  {
    id: 7,
    title: 'Burger',
    category: 'lunch',
    price: 12.99,
    img: './images/item-7.jpeg',
    desc: `Quis varius quam quisque id diam vel quam elementum. Dapibus ultrices in iaculis nunc sed augue lacus. Fames ac turpis egestas maecenas pharetra. Imperdiet nulla malesuada pellentesque elit.`,
  },
  {
    id: 8,
    title: 'Small Burger and Fries',
    category: 'lunch',
    price: 16.99,
    img: './images/item-8.jpeg',
    desc: `Fames ac turpis egestas integer eget aliquet nibh praesent. Nulla pharetra diam sit amet nisl suscipit adipiscing. Malesuada fames ac turpis egestas maecenas pharetra convallis. Netus et malesuada fames ac.`,
  },
  {
    id: 9,
    title: 'Flavor Drink',
    category: 'snacks',
    price: 20.99,
    img: './images/item-9.jpeg',
    desc: `Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices.`,
  },
];
export default menu;
